#' learn_interface UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd
#'
#' @importFrom shiny NS tagList
mod_learn_interface_ui <- function(id){
  ns <- NS(id)
  tagList(
    fluidRow(
      column(width = 6, offset = 3,
        tags$br(),
        tags$h3("Workflow"),
        tags$p("The interface implements a complete workflow of statistical analyses, from data description, model fitting, diagnostics, to result presentation."),
        tags$ul(
          tags$li("First, the interface reads and displays the input data."),
          tags$li("Second, it presents descriptive statistics of the patient records and geographic areas, where examples of raw data are also displayed."),
          tags$li("Third, users can specify and fit different models with various choices of covariates and fixed/varying effects. The model fitting is via Bayesian computation with Markov chain Monte Carlo algorithms in Stan. Model summaries are shown."),
          tags$li("Fourth, the interface shows a comparison between different models and presents their diagnostics results."),
          tags$li("Finally, interface graphs demonstrate the estimated infection prevalence over time for the targeted population and demographic and geographic subpopulations, for the selected model."),
        ),
        tags$h3("Uploading Data"),
        tags$p("The interface expect the input data to be in either of the following forms: \"individual cells\" in which each row contains information about an individual person and \"aggregated cells\" which contains the population count for each unique combination of relevant geographic-demographic factors. The latter is preferred as it offers computational advantages over its counterpart. The statistical models generated by the interface requires categorical quantities. In the future, users will be able to specify the categories to convert raw values into, but the interface currently expects the following grouping in the input data (The values in parentheses are the corresponding values expected in the input data)."),
        tags$h5("Cross-sectional Data"),
        tags$ul(
          tags$li("Sex: male, female"),
          tags$li("Race: Black, White, Hispanic, other"),
          tags$li("Age (in years): 18-29, 30-39, 40-49, 50-59, 60-69, 70+"),
          tags$li("Education level: below high school (no hs), high school (hs), some college, 4-year college, post-grad"),
          tags$li("State: each state is treated as a category. Full names, abbreviations and FIPS codes are accepted.")
        ),
        tags$h5("Spatio-temporal Data"),
        tags$ul(
          tags$li("Sex: male, female"),
          tags$li("Race: Black, White, other"),
          tags$li("Age (in years): 0-17, 18-34, 35-64, 65-74, 75+"),
          tags$li("ZIP code: each ZIP code is treated as a category"),
          tags$li("Week index: test result dates are grouped into weeks with index 1 assigned to the earliest week in the data. An optional column containing the date of the first day of each week can be included for visualization purposes. Currently, the only accepted format is yyyy-mm-dd.")
        ),
        tags$p("Users can manually aggregate their raw data if the interface cannot preprocess it or if they want more control over the process. Users familiar with R can download the preprocessing code below and modifies it as needed. The preprocessed or aggregated data must have the categorical values as described above in the right format or it will not be accepted. It also must have the right column names (see table below) as the interface uses one to extract data from the input table but it can automatically fix minor deviations such as letter case."),
        tags$p("Below is a simulated dataset that exemplifies the expected aggregated data input."),
        tabsetPanel(
          tabPanel("Cross-sectional",
            tags$div(class = "pad_top",
              DT::dataTableOutput(outputId = ns("example_cs"))
            ),
            tags$div(
              class = "interface_buttons",
              downloadButton(
                outputId = ns("save_code_cs"),
                label = "Preprocessing code"
              ),
              downloadButton(
                outputId = ns("save_ex_w_state"),
                label = "Example data (with states)"
              ),
              downloadButton(
                outputId = ns("save_ex_wo_state"),
                label = "Example data (without states)"
              )
            )
          ),
          tabPanel("Spatio-temporal",
            tags$div(class = "pad_top",
              DT::dataTableOutput(outputId = ns("example_st"))
            ),
            tags$div(
              class = "interface_buttons",
              downloadButton(
                outputId = ns("save_code_st"),
                label = "Preprocessing code"
              ),
              downloadButton(
                outputId = ns("save_ex_st"),
                label = "Example data"
              ),
              downloadButton(
                outputId = ns("save_week_table"),
                label = "Week conversion table"
              )
            )
          )
        ),
        tags$h3("Fitting & Comparing Models"),
        tags$p("Users can select variables to include in a model and specify whether they are fixed or varying effects through simple drag-and-drop interactions. The variables are divided into four categories:"),
        tags$ul(
          tags$li(tags$b("Individual-level Predictors"), " are demographic information about the patients associated with the provided test records."),
          tags$li("The ", tags$b("Geographic-area-level Indicator"), " allows models to utilize quantities defined at the geographic-area level such as state or ZIP code."),
          tags$li(tags$b("Geographic-area-level Predictors"), " includes relevant quantities that are retrieved from the external data sources such as the American Census Survey (ACS) and linked to individual records through ZIP codes or states."),
          tags$li(tags$b("Interactions"), " can be included in models to account for how the effect of one predictor is conditioned on that of another.")
        ),
        tags$p("The model fitting process involves generating MCMC chains which are usually done in parallel to reduce runtime

               . The interface automatically use one core for each chain so the user must choose the number of chains carefully based on the available computing resouces. Learn more about sampling ",
               tags$a("here", href = "https://paul-buerkner.github.io/brms/articles/brms_threading.html", target = "_blank", class = "action_link"), "."),
        tags$p("For spatio-temporal data, we expect test records for infectious diseases such as COVID-19. Because test results are not always accurate, the models generated by the interface automatically include specificity and sensitivity to account for the false positive and false negative results. Refer to this ", tags$a("paper", href = "https://academic.oup.com/jrsssc/article/69/5/1269/7058663", target = "_blank"), " by Andrew Gelman and Bob Carpenter for more details about this approach.")
      )
    )
  )
}

#' learn_interface Server Functions
#'
#' @noRd
mod_learn_interface_server <- function(id, global){
  moduleServer( id, function(input, output, session){
    ns <- session$ns

    output$example_cs <- DT::renderDataTable({
      read.csv(app_sys("extdata/example_cs_w_state.csv"))
    })

    output$example_st <- DT::renderDataTable({
      read.csv(app_sys("extdata/example_st.csv"))
    })

    output$save_code_cs <- downloadHandler(
      filename = function() { "preprocess.R" },
      content = function(file) {
        readLines(app_sys("extdata/preprocess_cs.R")) |> writeLines(file)
      }
    )

    output$save_code_st <- downloadHandler(
      filename = function() { "preprocess.R" },
      content = function(file) {
        readLines(app_sys("extdata/preprocess_st.R")) |> writeLines(file)
      }
    )

    output$save_ex_w_state <- downloadHandler(
      filename = function() { "example_cs_w_state.csv" },
      content = function(file) {
        read.csv(app_sys("extdata/example_cs_w_state.csv")) |> write.csv(file, row.names = FALSE)
      }
    )

    output$save_ex_wo_state <- downloadHandler(
      filename = function() { "example_cs_wo_state.csv" },
      content = function(file) {
        read.csv(app_sys("extdata/example_cs_wo_state.csv")) |> write.csv(file, row.names = FALSE)
      }
    )

    output$save_ex_st <- downloadHandler(
      filename = function() { "example_st.csv" },
      content = function(file) {
        read.csv(app_sys("extdata/example_st.csv")) |> write.csv(file, row.names = FALSE)
      }
    )

    output$save_week_table <- downloadHandler(
      filename = function() { "week_conversion.csv" },
      content = function(file) {
        read.csv(app_sys("extdata/week_conversion.csv")) |> write.csv(file, row.names = FALSE)
      }
    )

    outputOptions(output, "example_cs", suspendWhenHidden = FALSE)
    outputOptions(output, "example_st", suspendWhenHidden = FALSE)
  })
}
